server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transfer?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: MySQL@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # http://blog.didispace.com/Springboot-2-0-HikariCP-default-reason/
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: TransferHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
logging:
  level:
    com.xiaozhangge.transfer.mapper: debug
